services:
  - type: web
    name: deespora-backend
    env: node
    plan: free
    rootDir: .              
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
